services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - DATABASE_URL=postgres://feverish:feverish@db:5432/feverish
      - DEBUG=True
    depends_on:
      - db

  worker:
    build: .
    command: /bin/bash /app/scripts/background_refresh.sh
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://feverish:feverish@db:5432/feverish
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=feverish
      - POSTGRES_USER=feverish
      - POSTGRES_PASSWORD=feverish

volumes:
  postgres_data:
