[project]
name = "fever"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "djangorestframework>=3.16.1",
    "feedparser>=6.0.12",
    "python-dateutil>=2.9.0.post0",
]
